### ISSUE TITLE
I see ERR Illegal value for `line`: Error: Illegal value for `line` for a file

### ISSUE THREAD

**Issue by capaj** [SirTori/indenticator#20]
```
 ERR Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:460:662)
    at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:459:416)
    at IndentSpy._getSelectedIndentDepth (/home/capaj/.vscode/extensions/SirTori.indenticator-0.5.1/out/src/extension.js:320:33)
    at IndentSpy.updateCurrentIndent (/home/capaj/.vscode/extensions/SirTori.indenticator-0.5.1/out/src/extension.js:169:35)
    at IndentSpyController._onUpdateEvent (/home/capaj/.vscode/extensions/SirTori.indenticator-0.5.1/out/src/extension.js:425:25)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:516)
    at e.$acceptEditorPropertiesChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:689:401)
    at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:894)
    at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:612)
    at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:597:682)
    at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:597:451)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:596:384
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:463
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:119
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:145:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

I can provide you the file via DM if you want.

**Comment by SirTori** [comment]
Hi,
thanks for you feedback. I looked into the source code at the place indicated by the stacktrace and added some additional checks. So this should no longer happen.

If it does keep happening with Version 0.6.0 please let me know and send me the file you mentioned so I can take a look at you specific case.

regards,
SirTori
