### ISSUE TITLE
 TypeError: Cannot read property 'peekBack' of undefined

### ISSUE THREAD

**Issue by capaj** [SirTori/indenticator#25]
```
Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (/home/capaj/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:250:28)
	at IndentSpy._buildHoverString (/home/capaj/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:234:35)
	at IndentSpy._buildHoverprovider (/home/capaj/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:215:28)
	at Object.provideHover (/home/capaj/.vscode/extensions/sirtori.indenticator-0.6.0/out/src/extension.js:205:29)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:629:536
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:761
	at new Promise (<anonymous>)
	at Object.t.asPromise (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:733)
	at S.provideHover (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:629:507)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:220
	at e._withAdapter (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:649:159)
	at e.$provideHover (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:198)
	at e._doInvokeHandler (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:683)
	at e._invokeHandler (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:375)
	at e._receiveRequest (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:953)
	at e._receiveOneMessage (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:749:832)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:34
	at e.fire (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:919:744
	at e.fire (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:211:17)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:208:155
	at e.fire (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at p.acceptChunk (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:204:129)
	at /snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:203:483
	at Socket.t (/snap/code/31/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

got this with version 0.6.0.

**Comment by SirTori** [comment]
Thanks for bringing this to my attention.
While I cannot reproduce this, I will add checks in the next release to ensure this error won't happen
