### ISSUE TITLE
Illegal value for `line`: Error: Illegal value for `line`

### ISSUE THREAD

**Issue by kurtextrem** [SirTori/indenticator#8]
Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:229497)
    at Object.lineAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:228287)
    at IndentSpy._getSelectedIndentDepth (C:\Users\admin\.vscode-insiders\extensions\SirTori.indenticator-0.4.2\out\src\extension.js:267:33)
    at IndentSpy.updateCurrentIndent (C:\Users\admin\.vscode-insiders\extensions\SirTori.indenticator-0.4.2\out\src\extension.js:128:35)
    at IndentSpyController._onUpdateEvent (C:\Users\admin\.vscode-insiders\extensions\SirTori.indenticator-0.4.2\out\src\extension.js:340:25)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30930)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34737)
    at t.$acceptSelectionsChanged (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:347776)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266430)
    at s (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154933)
    at h (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155610)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by SirTori** [comment]
I could not reproduce the error and since nobody else came across it I will closet his issue for now. If you can give me way to reproduce it I will look into this further and reopen this issue
